spring.application.name=finsight-ai

spring.datasource.url=jdbc:postgresql://localhost:5432/finsight
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=krupa
spring.security.user.password=1234

server.port=8081